### ISSUE TITLE
documentation

### ISSUE THREAD

**Issue by barbarerik** [ultamatum/P5-Project-Creator#3]
Hi I am totally new in programing. 
Could you pleas add some basic documentation, like  how to call new project?
I have found some tutorial on Youtube how to call new P5 project, but terrifying to go for such information to Youtube :)
It would be faster to know it from info page.

thanks for your plugin

**Comment by ultamatum** [comment]
Hi,

Apologies for just getting back to you.

If you have the extension installed in VSCode just use CTRL+SHIFT+P to
bring up the command palette and type in "Create P5 Project", the
extension's command should come up, click on it and it'll ask for a name
for the project.

Hope this helps
Thanks
-Alexander

**Comment by ultamatum** [comment]
Will add this to README when I get a minute
